### ISSUE TITLE
Check for unused function parameters

### ISSUE THREAD

**Issue by martinj** [aptoma/eslint-config#11]
We are currently ignoring checking use of function parameters.
`'no-unused-vars': [2, {'vars': 'all', 'args': 'none'}],`

Any objections to enable this with the feature `after-used`
`after-used` will allow the follow

```javascript

search((idx, item) => {
 return item;
});

```

Or to check all and ignore manually ignore examples as above.

**Comment by mipli** [comment]
Enabling it with `after-used` sounds good to me.

**Comment by gunnarlium** [comment]
As long we include `after-used`. As the arguments will often be defined by 3rd party providers, it's a needless hassle to manually ignore every time.

My editor still gives a warning on those.
