### ISSUE TITLE
Set "arrow-parens" to "as-needed" instead of "always" ?

### ISSUE THREAD

**Issue by pahen** [aptoma/eslint-config#17]
See https://eslint.org/docs/rules/arrow-parens#as-needed

**Comment by gunnarlium** [comment]
I disapprove. There's virtually no overhead in adding parens. Using parens is clearer and more consistent, and requires no change when adding/removing a parameter.

**Comment by mipli** [comment]
I agree with Gunnar. I think we should keep the parens, not enough to gain by removing them when they're needed for functions with more than one parameter.

**Comment by pahen** [comment]
Ok, valid arguments. I'll close :)
